version: '3.4'

x-logging:
  &default-logging
  driver: journald


services:
  tailscale-plugin:
    container_name: tailscale-plugin
    build:
      context: .
    logging: *default-logging
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
    cap_add:
      - NET_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.route_localnet=1
    networks:
      tailscalenet:
    volumes:
      - "${SUPERDIR}./state/plugins/tailscale:/state/plugins/tailscale"
      - "${SUPERDIR}./state/public/:/state/public/:ro"
      - "${SUPERDIR}./state/api/:/state/api/:ro"
      - "${SUPERDIR}./configs/plugins/tailscale:/configs/tailscale"
      - "${SUPERDIR}./state/plugins/tailscale/varlib:/var/lib"
      - /dev/net/tun:/dev/net/tun

networks:
  tailscalenet:
    driver_opts:
      com.docker.network.bridge.name: tailscale
